### PR TITLE
Added ddpg agent(PID)

### PR DESCRIPTION
**Pull request by rudrasohan**
-DDPG agent added.
-To test `python3 -m sample_DDPG/playGame_DDPG_pid 3001`

### CODE REVIEW

**Comment by rudrasohan** [comment]
To be done after #1 and #2 are merged

**Comment by MehaKaushik** [comment]
@rudrasohan you again did not add a proper PR description. How do I validate if everything is working ? Even after checking it out locally I do not know what all should I run to test the correctness of everything !!!

**Comment by rudrasohan** [comment]
This was a [WIP]  old PR I was waiting for #4 to get merged as it changes the structure of the repo. I will update it accordingly by today evening.

**Comment by rudrasohan** [comment]
Am closing this for now. Let me do a fresh PR.

**Pull request closed without merging**
